# Python

# 1.Write a program using list comprehension to find primes in range 2 to 100.

In [18]:
list=range(2,101)

In [24]:
prime_list=[]
for i in list:
    n=0
    for j in range(1,i+1):
        if i%j==0:
            n+=1
        if n>2:
            break;

    if(n==2):
        prime_list.append(i)
            

In [25]:
prime_list

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

In [26]:
len(prime_list)

25

# 2.Write a function to reverse a string

# string='reverse a string'

In [66]:
def reverse_string(string):
    list=[]
    list.extend(string)
    re_string=''
    for i in list[-1::-1]:
        p=str(i)
        re_string=re_string+p
    return(re_string)

In [71]:
reverse_string('koushik biswas')

'sawsib kihsuok'

In [82]:
#another simple function

def re_string(input):
    if type(input)==int:
        print("Enter a string type value")
    else:
        return input[::-1]

In [83]:
re_string('koushik')

'kihsuok'

 # 3.Write a program to extract the words from the given list which have their first character in uppercase. Days = ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']   Output: ['Monday', 'Sunday', 'Saturday']

In [85]:
Days = ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']

In [86]:
output=[]
for i in Days:
    if i[0].isupper():
        output.append(i)
    

In [87]:
output

['Monday', 'Sunday', 'Saturday']

# 5.Write a program swap the keys to values and values to keys of the given dictionary. Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'Big Data':4} Output: {1:'Data Science',2:'Machine Learning', 3:'SQL', 4:'Big Data'}

In [2]:
Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'Big Data':4}

In [7]:
Module.keys()

dict_keys(['Data Science', 'Machine Learning', 'SQL', 'Big Data'])

In [18]:
Module.values()

dict_values([1, 2, 3, 4])

In [24]:
for key , value in Module.items(): 
    print(key)
    print(value)

Data Science
1
Machine Learning
2
SQL
3
Big Data
4


In [26]:
output={}
for key , value in Module.items():
    output[value]=key

In [27]:
output

{1: 'Data Science', 2: 'Machine Learning', 3: 'SQL', 4: 'Big Data'}

# 6.Write a program to count the number of elements in the string (given by the user) that are not present in the 'my_string'. Do not count the white spaces. my_string = 'Data Science'

In [99]:
user_string=input("INPUT A STRING: ")
x=set(my_string.lower().replace(" ",''))
y=set(user_string.lower().replace(" ",''))
print("Number of elements in the user_string not present in my_string:",len(y-x))

INPUT A STRING: Data Science
Number of elements in the user_string not present in my_string: 0


# 7.Define a function to check whether a number is in a range (1000,10000) or not.

In [40]:
def range_fun(number):
    if number>1000 and number<10000:
        print("The given number:",number,"is belong to the range(1000,10000)")
        
    else:
        print("The given number:",number,"is not belong to the range(1000,10000)")

In [42]:
range_fun(1200)

The given number: 1200 is belong to the range(1000,10000)


In [43]:
range_fun(100)

The given number: 100 is not belong to the range(1000,10000)


# 8.Write a program to calculate the sum of all elements in the list.       test_score = [10, 32, 23, 14, 25]

In [44]:
test_score = [10, 32, 23, 14, 25]

In [45]:
sum=0
for i in test_score:
    sum=sum+i
    
print("sum of the all values in test_score is =",sum)

sum of the all values in test_score is = 104


# 9.Replace all even numbers in the array with -1.Use the array given below num_array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])

In [62]:
import numpy as np

In [63]:
num_array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])

In [64]:
num_array[1]

21

In [65]:
for j in range(0,len(num_array)):
    if j%2==1:
        num_array[j]=-1
            
num_array

array([ 0, -1, 32, -1, 44, -1, 26, -1, 38, -1, 65, -1, 76])

# 10.Find the minimum value along each of the rows. Create a 2D Numpy array from list of lists Score = np.array([[210, 402, 383], [140, 375, 106], [140, 125, 217], [292, 240, 295]])

In [67]:
Score = np.array([[210, 402, 383], [140, 375, 106], [140, 125, 217], [292, 240, 295]])

In [68]:
Score

array([[210, 402, 383],
       [140, 375, 106],
       [140, 125, 217],
       [292, 240, 295]])

In [76]:
Score[0]

array([210, 402, 383])

In [75]:
Score[0].min()

210

In [72]:
len(Score)

4

In [80]:
for i in range(0,len(Score)):
    min=Score[i].min()
    print("The minimum value of",Score[i],"=",min)

The minimum value of [210 402 383] = 210
The minimum value of [140 375 106] = 106
The minimum value of [140 125 217] = 125
The minimum value of [292 240 295] = 240


In [83]:
list=[[210, 402, 383], [140, 375, 106], [140, 125, 217], [292, 240, 295]]
array_2D=np.array(list)
array_2D

array([[210, 402, 383],
       [140, 375, 106],
       [140, 125, 217],
       [292, 240, 295]])